name:                GLaDOS
version:             0.1.0.0
github:              "ThibautHH/GLaDOS"
license:             BSD-3-Clause
author:              "Thibaut Hebert--Henriette"
maintainer:          "thibaut.hebert-henriette@epitech.eu"
copyright:           "(c) Thibaut Hebert--Henriette 2024"

extra-doc-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Interpreter

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ThibautHH/GLaDOS#readme>

dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - composition-prelude
  - transformers
  - monad-loops
  - text
  - binary
  - bytestring
  - array
  - containers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

build-tools:
  - alex

library:
  source-dirs: src

executables:
  GLaDOS-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - GLaDOS

tests:
  GLaDOS-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - GLaDOS
      - hspec
      - hspec-megaparsec
