site_name: FunChill Documentation

theme:
  name: null
  custom_dir: 'cinder'

nav:
  - Home: index.md
  - Intro: introduction.md
  - Reference:
    - Index: reference/index.md
    - Operators: reference/operator_table.md
    - Keywords: reference/keywords.md
    - Types: reference/types.md
    - Expressions: reference/expressions.md
    - Statements: reference/statements.md
    - Whitespace: reference/whitespace.md
    - Grammar: reference/grammar.md
  - About: about.md

plugins:
  - search
  - macros
